### ISSUE TITLE
Very low energy consumption

### ISSUE THREAD

**Issue by ShalokShalom** [ColinIanKing/powerstat#1]
hi :hugs: 

this is my system: i5 3570k - RX 480 - Z68 Pro3 Gen3 

powerstat shows a consumption of 8.64 watts; while the browser is open and a song plays in it.

can this be possible?

current git

**Comment by ColinIanKing** [comment]
It depends on how you measured the power. If one uses the RAPL option -R then powerstat only measures what it can find from the intel power interfaces.   Using the battery drain default option and running powerstat for a long duration will measure the power drain from the battery and this covers all the power including wifi, bluetooth, ssd/hdd drive power and laptop display drain.
