### ISSUE TITLE
0 W value in Debian

### ISSUE THREAD

**Issue by raul-parada** [ColinIanKing/powerstat#3]
I've run powerstat in a Raspbian (debian distribution) [https://www.raspberrypi.org/software/raspberry-pi-desktop/] on a virtualbox 
and I get 0.00E as Watts. See image below.

![image](https://user-images.githubusercontent.com/8438920/108877546-a0cf9100-75ff-11eb-8479-437a4037aea7.png)

Why I'm not getting values?

**Comment by ColinIanKing** [comment]
The code was originally developed for x86 systems that provide power stats from /sys - I don't believe the RaspberryPi exports these stats, so the Watts figure is zero (as noted by the E flag (Error/Estimated).
