### ISSUE TITLE
0 watts value in Ubuntu

### ISSUE THREAD

**Issue by Mo7ammed7akimi** [ColinIanKing/powerstat#7]
I've run powerstat in ubuntu, facing an issue there is no watts values with the samples. Details and image as below:

Ubuntu 5.19.0-38.39~22.04.1-generic 5.19.17

model name	: Intel(R) Core(TM) i5 CPU         750  @ 2.67GHz

![image](https://user-images.githubusercontent.com/26076563/230835957-c07bfc29-354c-4d9e-9c10-94a24100cbdc.png)

**Comment by ColinIanKing** [comment]
How are you running the powerstat tool?

**Comment by ColinIanKing** [comment]
No response since April. Closing issue.
