### ISSUE TITLE
netlink_listen return -1 inside container with root priviledge

### ISSUE THREAD

**Issue by MichaelZhangBH** [ColinIanKing/powerstat#8]
There is no output inside container.
![image](https://user-images.githubusercontent.com/97571699/231055465-36e24b16-2619-4ab3-9e68-176759393dd4.png)

I've narrowed down the issue to https://github.com/ColinIanKing/powerstat/blob/master/powerstat.c#L3152, `netlink_listen` will return -1. Maybe you can have a look. 

Thank you!

**Comment by ColinIanKing** [comment]
Thanks for reporting this issue. Fix committed.
